In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("Ads.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
X=data.iloc[:,2:4].values

In [4]:
X.shape

(400, 2)

In [5]:
y=data.iloc[:,-1].values

In [6]:
y.shape

(400,)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [8]:
X_train.shape

(320, 2)

In [9]:
X_test.shape

(80, 2)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [11]:
X_train=scaler.fit_transform(X_train)
X_train

array([[ 0.91161504, -1.31630957],
       [ 0.91161504,  1.03917239],
       [ 1.98410332,  0.74473715],
       [ 0.71661717, -1.40464014],
       [-0.64836792,  0.12642313],
       [-0.55086898, -1.52241424],
       [ 0.2291225 , -0.31522973],
       [ 0.32662143,  0.06753608],
       [ 1.59410758,  0.00864904],
       [ 1.00911397,  0.77418067],
       [-0.74586685,  1.36305116],
       [-0.45337005, -0.28578621],
       [ 1.98410332, -0.66855203],
       [-0.64836792,  0.03809256],
       [ 1.00911397, -1.02187432],
       [ 2.08160226,  0.39141485],
       [-1.33086046, -0.43300383],
       [ 1.30161078,  2.2463569 ],
       [-0.06337431,  2.2463569 ],
       [-0.74586685,  0.50918895],
       [-0.06337431,  0.27364076],
       [-1.03836366, -1.55185777],
       [-0.64836792,  1.42193821],
       [ 1.59410758,  1.12750297],
       [-0.06337431, -0.52133441],
       [-0.16087324, -0.52133441],
       [ 0.2291225 ,  0.15586666],
       [ 0.03412463, -0.25634269],
       [-1.62335726,

In [12]:
X_test=scaler.transform(X_test)
X_test

array([[-1.03836366,  0.568076  ],
       [-1.13586259, -1.55185777],
       [-0.64836792,  0.568076  ],
       [-1.33086046,  0.42085838],
       [-0.74586685, -1.55185777],
       [-1.13586259,  0.30308428],
       [ 2.08160226,  1.77526051],
       [ 0.13162356,  0.03809256],
       [-0.25837218,  0.09697961],
       [ 2.08160226, -0.81576965],
       [-1.23336152,  0.30308428],
       [ 1.88660439, -1.08076137],
       [-0.16087324,  0.15586666],
       [ 0.81411611,  1.39249469],
       [-0.74586685,  0.30308428],
       [-1.62335726, -0.05023801],
       [-0.64836792, -0.05023801],
       [-1.23336152,  0.59751953],
       [ 0.71661717,  0.27364076],
       [-1.03836366, -0.34467326],
       [-0.06337431,  2.18746985],
       [-0.25837218, -0.31522973],
       [ 2.17910119,  0.39141485],
       [ 0.81411611, -0.31522973],
       [-0.25837218, -0.28578621],
       [-0.25837218,  0.06753608],
       [ 0.2291225 , -0.25634269],
       [ 0.03412463, -0.13856859],
       [-1.7208562 ,

In [13]:
## Method for chosing k
np.sqrt(X_train.shape[0])

17.88854381999832

In [15]:
#k=17

In [25]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=17)  ##n_neighbors=k

In [26]:
# Train our model
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [27]:
y_pred=knn.predict(X_test)

In [28]:
y_pred.shape

(80,)

In [29]:
y_test.shape

(80,)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.925

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[51,  6],
       [ 0, 23]], dtype=int64)

In [32]:
accuracy_score(y_test,y_pred)

0.925