In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression , Lasso  , Ridge

%matplotlib inline

In [2]:
df_mob = pd.read_csv("Cellphone.csv")

In [3]:
df_mob.head()

Product_id  Price  Sale  weight  resoloution  cpucore  internal mem    ram  \
0         203   2357    10   135.0          5.2        8          16.0  3.000   
1         880   1749    10   125.0          4.0        2           4.0  1.000   
2          40   1916    10   110.0          4.7        4           8.0  1.500   
3          99   1315    11   118.5          4.0        2           4.0  0.512   
4         880   1749    11   125.0          4.0        2           4.0  1.000   

   battery  
0     2610  
1     1700  
2     2000  
3     1400  
4     1700

In [4]:
df_mob.tail()

Product_id  Price  Sale  weight  resoloution  cpucore  internal mem  ram  \
156        1206   3551  4638   178.0         5.46        4         128.0  6.0   
157        1296   3211  8016   170.0         5.50        4         128.0  6.0   
158         856   3260  8809   150.0         5.50        8          64.0  4.0   
159        1296   3211  8946   170.0         5.50        4         128.0  6.0   
160        1131   2536  9807   202.0         6.00        8          16.0  3.0   

     battery  
156     4080  
157     3400  
158     3000  
159     3400  
160     2700

In [5]:
df_mob.isna().sum()

Product_id      0
Price           0
Sale            0
weight          0
resoloution     0
cpucore         0
internal mem    0
ram             0
battery         0
dtype: int64

In [12]:
df_mob = df_mob.drop("Product_id",axis=1)


In [13]:
df_mob

Price  Sale  weight  resoloution  cpucore  internal mem    ram  battery
0     2357    10   135.0         5.20        8          16.0  3.000     2610
1     1749    10   125.0         4.00        2           4.0  1.000     1700
2     1916    10   110.0         4.70        4           8.0  1.500     2000
3     1315    11   118.5         4.00        2           4.0  0.512     1400
4     1749    11   125.0         4.00        2           4.0  1.000     1700
..     ...   ...     ...          ...      ...           ...    ...      ...
156   3551  4638   178.0         5.46        4         128.0  6.000     4080
157   3211  8016   170.0         5.50        4         128.0  6.000     3400
158   3260  8809   150.0         5.50        8          64.0  4.000     3000
159   3211  8946   170.0         5.50        4         128.0  6.000     3400
160   2536  9807   202.0         6.00        8          16.0  3.000     2700

[161 rows x 8 columns]

In [15]:
X = df_mob.drop('Price', axis=1)
X

Sale  weight  resoloution  cpucore  internal mem    ram  battery
0      10   135.0         5.20        8          16.0  3.000     2610
1      10   125.0         4.00        2           4.0  1.000     1700
2      10   110.0         4.70        4           8.0  1.500     2000
3      11   118.5         4.00        2           4.0  0.512     1400
4      11   125.0         4.00        2           4.0  1.000     1700
..    ...     ...          ...      ...           ...    ...      ...
156  4638   178.0         5.46        4         128.0  6.000     4080
157  8016   170.0         5.50        4         128.0  6.000     3400
158  8809   150.0         5.50        8          64.0  4.000     3000
159  8946   170.0         5.50        4         128.0  6.000     3400
160  9807   202.0         6.00        8          16.0  3.000     2700

[161 rows x 7 columns]

In [17]:
y = df_mob['Price']
y

0      2357
1      1749
2      1916
3      1315
4      1749
       ... 
156    3551
157    3211
158    3260
159    3211
160    2536
Name: Price, Length: 161, dtype: int64

## Splitting Data

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [21]:
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (112, 7)
Shape of y_train =  (112,)
Shape of X_test =  (49, 7)
Shape of y_test =  (49,)


## Scaling Price

In [22]:
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Linear Model

In [23]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [24]:
lr.coef_

array([ -43.24730536, -354.54072917,  231.55434863,  193.14973528,
        149.2279405 ,  317.08340622,  187.00264443])

In [25]:
lr.intercept_

2189.2142857142862

In [31]:
X_test

array([[-3.48793598e-01,  1.83136793e-01,  2.95660806e-01,
         4.81907593e-01,  3.42746928e-01,  5.19603538e-01,
         7.46595555e-01],
       [-1.93658464e-01, -1.56779289e-01,  2.95660806e-01,
         1.30593279e+00,  3.42746928e-01,  5.19603538e-01,
         2.94064425e-01],
       [-3.52771422e-01,  1.29440091e+00,  1.42326615e+00,
        -1.16614280e+00, -7.32800090e-01, -1.03594699e+00,
         1.31153219e-01],
       [-2.55977706e-01, -1.07978219e+00, -2.03472357e+00,
        -1.99016800e+00, -8.86449664e-01, -1.35105852e+00,
        -1.42555387e+00],
       [-1.46587548e-01, -5.62063848e-01, -8.31944538e-01,
        -3.42117604e-01, -7.32800090e-01, -1.03594699e+00,
        -8.55364645e-01],
       [-1.41946753e-01,  1.04694620e-01,  2.95660806e-01,
         1.30593279e+00, -2.71851368e-01, -1.05617737e-01,
         8.64253649e-01],
       [ 2.52518420e+00,  2.22357879e-01,  2.65591330e-01,
        -3.42117604e-01,  4.03033670e+00,  2.39526736e+00,
         1.2715316

In [28]:
lr.predict(X_test)

array([2656.43150719, 2844.7721568 , 1436.56629981,  900.298246  ,
       1538.31672841, 2566.49697757, 3595.30901554, 1827.01679509,
       2656.8615826 , 2409.79556864, 1448.90009615, 2440.43416769,
       2213.74258999, 1691.01072884, 2457.55883135, 1740.78291436,
        684.51978602, 2436.32297938, 2155.65893285, 2409.65221017,
       2159.92490899, 2307.26758447, 1702.64731867, 2792.66721328,
       2721.0504723 , 2015.37417686, 3247.86617217, 1660.83923449,
       2348.92171467, 1567.67431244, 3222.00430377, 1741.18431809,
       3125.54131011, 2363.3423887 ,  856.80969442, 2015.08745992,
        832.19334241, 4203.5298368 , 1504.22197561, 2807.57820419,
       4204.76271966, 3679.09894403, 2155.64358886, 2271.27173578,
       2722.79507136, 2213.6852466 , 3042.5719236 , 1454.00701309,
       1331.50923102])

In [29]:
y_test

65     2824
112    2975
62     1347
105     833
119    1734
121    2054
155    3551
144    1921
60     2824
78     2714
4      1749
136    2445
37     2124
95     1810
96     2562
59     1741
126     705
13     2744
7      2137
80     2714
9      2580
127    2491
70     1734
39     2392
17     2938
24     1942
73     3116
48     1843
143    2508
102    1522
137    3116
50     1741
10     2438
41     2087
113     754
36     1942
81      791
153    4361
90     1646
49     2685
152    4361
87     3837
26     2006
160    2536
147    3102
40     2124
61     2746
130    1357
3      1315
Name: Price, dtype: int64

## Score -- Model

In [37]:
lr.score(X_test, y_test)

0.9290260114609914

## Implementing Other Reg Models

In [33]:
ls = Lasso()
ls.fit(X_train,y_train)
ls.predict(X_test)

array([2652.95050402, 2842.99288868, 1434.0626702 ,  903.9099932 ,
       1540.29267736, 2562.10373203, 3590.21951053, 1823.07860694,
       2653.36821844, 2412.75039614, 1451.00886877, 2435.90149766,
       2204.16362505, 1698.25896446, 2458.25605307, 1740.30972512,
        696.8115496 , 2433.25401357, 2151.06949102, 2412.611158  ,
       2154.75568371, 2322.86993432, 1703.57435782, 2792.9663702 ,
       2717.06877563, 2016.19829706, 3245.40561712, 1664.17778857,
       2346.30722313, 1564.20632402, 3220.28705667, 1740.69959191,
       3122.55750968, 2363.3722759 ,  862.26224809, 2015.91982078,
        842.68655038, 4189.89502073, 1512.26616506, 2807.34404813,
       4191.09246873, 3672.41342668, 2156.04186185, 2287.19334905,
       2724.84602309, 2204.10792979, 3030.1185755 , 1452.69671155,
       1333.28202818])

In [34]:
ls.score(X_test, y_test)

0.9296736721072755

In [35]:
rg = Ridge()
rg.fit(X_train,y_train)
rg.predict(X_test)

array([2651.05840391, 2843.29393457, 1429.52844692,  909.89813575,
       1544.79227841, 2559.50379563, 3595.71964975, 1812.06326652,
       2651.51103688, 2417.82098403, 1451.5091246 , 2430.60683504,
       2194.07081414, 1710.14734255, 2460.77376435, 1741.93981474,
        713.69487155, 2428.73336258, 2142.68853177, 2417.67010638,
       2146.98176217, 2352.5367073 , 1703.68634487, 2797.28698609,
       2705.57526269, 2015.73393819, 3254.35475208, 1669.0752182 ,
       2330.20306944, 1554.90433258, 3227.13642289, 1742.36227218,
       3118.07533096, 2362.58785215,  869.84067966, 2015.43218288,
        860.1803543 , 4198.52377226, 1525.136595  , 2810.49539472,
       4199.8213201 , 3689.37829048, 2159.64171286, 2269.70541363,
       2725.35494079, 2194.01046308, 3023.58301383, 1455.03044448,
       1335.97695524])

In [36]:
rg.score(X_test, y_test)

0.9298734554723668